//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaOrder.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitOrderEntityMappings();
			InitOrderPizzaEntityMappings();
			InitPizzaEntityMappings();
			InitPizzaToppingEntityMappings();
			InitToppingEntityMappings();
		}

		/// <summary>Inits OrderEntity's mappings</summary>
		private void InitOrderEntityMappings()
		{
			this.AddElementMapping("OrderEntity", @"Pizza", @"public", "Order", 2, 0);
			this.AddElementFieldMapping("OrderEntity", "Id", "Id", false, "Bigint", 0, 20, 0, true, "public.Order_Id_seq", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("OrderEntity", "Name", "Name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits OrderPizzaEntity's mappings</summary>
		private void InitOrderPizzaEntityMappings()
		{
			this.AddElementMapping("OrderPizzaEntity", @"Pizza", @"public", "OrderPizza", 2, 0);
			this.AddElementFieldMapping("OrderPizzaEntity", "OrderId", "OrderId", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("OrderPizzaEntity", "PizzaId", "PizzaId", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
		}

		/// <summary>Inits PizzaEntity's mappings</summary>
		private void InitPizzaEntityMappings()
		{
			this.AddElementMapping("PizzaEntity", @"Pizza", @"public", "Pizza", 3, 0);
			this.AddElementFieldMapping("PizzaEntity", "Id", "Id", false, "Bigint", 0, 20, 0, true, "public.Pizza_Id_seq", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("PizzaEntity", "Name", "Name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("PizzaEntity", "Size", "Size", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 2);
		}

		/// <summary>Inits PizzaToppingEntity's mappings</summary>
		private void InitPizzaToppingEntityMappings()
		{
			this.AddElementMapping("PizzaToppingEntity", @"Pizza", @"public", "PizzaToppings", 2, 0);
			this.AddElementFieldMapping("PizzaToppingEntity", "PizzaId", "PizzaId", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("PizzaToppingEntity", "ToppingId", "ToppingId", false, "Bigint", 0, 20, 0, false, "", null, typeof(System.Int64), 1);
		}

		/// <summary>Inits ToppingEntity's mappings</summary>
		private void InitToppingEntityMappings()
		{
			this.AddElementMapping("ToppingEntity", @"Pizza", @"public", "Topping", 3, 0);
			this.AddElementFieldMapping("ToppingEntity", "Id", "Id", false, "Bigint", 0, 20, 0, true, "public.Topping_Id_seq", null, typeof(System.Int64), 0);
			this.AddElementFieldMapping("ToppingEntity", "Name", "Name", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("ToppingEntity", "Price", "Price", false, "Double", 0, 38, 0, false, "", null, typeof(System.Double), 2);
		}

	}
}
