//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace OrderWithPizza.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Order'.</summary>
	[Serializable]
	[DataContract]
	public partial class OrderWithPizza
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Order.Id'</summary>
		[DataMember]
		public System.Int64 Id { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Order.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the OrderPizzas field. </summary>
		[DataMember]
		public List<OrderWithPizzaTypes.OrderPizza> OrderPizzas { get; set; }
	}

	namespace OrderWithPizzaTypes
	{
		/// <summary> DTO class which is derived from the entity 'OrderPizza (OrderPizzas)'.</summary>
		[Serializable]
		[DataContract]
		public partial class OrderPizza
		{
			/// <summary>Gets or sets the PizzaId field. Derived from Entity Model Field 'OrderPizza.PizzaId (FK)'</summary>
			[DataMember]
			public System.Int64 PizzaId { get; set; }
		}
	}

}




