//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ToppingsOnPizza.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of ToppingsOnPizza.DtoClasses.ToppingsOnPizza from the entity model.</summary>
	public static partial class ToppingsOnPizzaPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<PizzaOrder.EntityClasses.PizzaEntity, ToppingsOnPizza.DtoClasses.ToppingsOnPizza>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<PizzaOrder.EntityClasses.PizzaEntity, ToppingsOnPizza.DtoClasses.ToppingsOnPizza> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static ToppingsOnPizzaPersistence() { }
	
		/// <summary>Extension method which produces a projection to ToppingsOnPizza.DtoClasses.ToppingsOnPizza which instances are projected from the 
		/// results of the specified baseQuery, which returns PizzaOrder.EntityClasses.PizzaEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve ToppingsOnPizza.DtoClasses.ToppingsOnPizza instances</returns>
		public static IQueryable<ToppingsOnPizza.DtoClasses.ToppingsOnPizza> ProjectToToppingsOnPizza(this IQueryable<PizzaOrder.EntityClasses.PizzaEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to ToppingsOnPizza.DtoClasses.ToppingsOnPizza which instances are projected from the
		/// PizzaOrder.EntityClasses.PizzaEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>PizzaOrder.EntityClasses.PizzaEntity instance created from the specified entity instance</returns>
		public static ToppingsOnPizza.DtoClasses.ToppingsOnPizza ProjectToToppingsOnPizza(this PizzaOrder.EntityClasses.PizzaEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<PizzaOrder.EntityClasses.PizzaEntity, ToppingsOnPizza.DtoClasses.ToppingsOnPizza>> CreateProjectionFunc()
		{
			return p__0 => new ToppingsOnPizza.DtoClasses.ToppingsOnPizza()
			{
				Id = p__0.Id,
				Name = p__0.Name,
				PizzaToppings = p__0.PizzaToppings.Select(p__1 => new ToppingsOnPizza.DtoClasses.ToppingsOnPizzaTypes.PizzaTopping()
				{
					Topping = new ToppingsOnPizza.DtoClasses.ToppingsOnPizzaTypes.PizzaToppingTypes.Topping()
					{
						Name = p__1.Topping.Name,
						Price = p__1.Topping.Price,
					},
				}).ToList(),
				Size = p__0.Size,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_ToppingsOnPizza 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

