//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using PizzaOrder.HelperClasses;
using PizzaOrder.FactoryClasses;
using PizzaOrder.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaOrder.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'OrderPizza'.<br/><br/></summary>
	[Serializable]
	public partial class OrderPizzaEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private OrderEntity _order;
		private PizzaEntity _pizza;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static OrderPizzaEntityStaticMetaData _staticMetaData = new OrderPizzaEntityStaticMetaData();
		private static OrderPizzaRelations _relationsFactory = new OrderPizzaRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Order</summary>
			public static readonly string Order = "Order";
			/// <summary>Member name Pizza</summary>
			public static readonly string Pizza = "Pizza";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class OrderPizzaEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public OrderPizzaEntityStaticMetaData()
			{
				SetEntityCoreInfo("OrderPizzaEntity", InheritanceHierarchyType.None, false, (int)PizzaOrder.EntityType.OrderPizzaEntity, typeof(OrderPizzaEntity), typeof(OrderPizzaEntityFactory), false);
				AddNavigatorMetaData<OrderPizzaEntity, OrderEntity>("Order", "OrderPizzas", (a, b) => a._order = b, a => a._order, (a, b) => a.Order = b, PizzaOrder.RelationClasses.StaticOrderPizzaRelations.OrderEntityUsingOrderIdStatic, ()=>new OrderPizzaRelations().OrderEntityUsingOrderId, null, new int[] { (int)OrderPizzaFieldIndex.OrderId }, null, true, (int)PizzaOrder.EntityType.OrderEntity);
				AddNavigatorMetaData<OrderPizzaEntity, PizzaEntity>("Pizza", "OrderPizzas", (a, b) => a._pizza = b, a => a._pizza, (a, b) => a.Pizza = b, PizzaOrder.RelationClasses.StaticOrderPizzaRelations.PizzaEntityUsingPizzaIdStatic, ()=>new OrderPizzaRelations().PizzaEntityUsingPizzaId, null, new int[] { (int)OrderPizzaFieldIndex.PizzaId }, null, true, (int)PizzaOrder.EntityType.PizzaEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static OrderPizzaEntity()
		{
		}

		/// <summary> CTor</summary>
		public OrderPizzaEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public OrderPizzaEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this OrderPizzaEntity</param>
		public OrderPizzaEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="orderId">PK value for OrderPizza which data should be fetched into this OrderPizza object</param>
		/// <param name="pizzaId">PK value for OrderPizza which data should be fetched into this OrderPizza object</param>
		public OrderPizzaEntity(System.Int64 orderId, System.Int64 pizzaId) : this(orderId, pizzaId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="orderId">PK value for OrderPizza which data should be fetched into this OrderPizza object</param>
		/// <param name="pizzaId">PK value for OrderPizza which data should be fetched into this OrderPizza object</param>
		/// <param name="validator">The custom validator object for this OrderPizzaEntity</param>
		public OrderPizzaEntity(System.Int64 orderId, System.Int64 pizzaId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.OrderId = orderId;
			this.PizzaId = pizzaId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected OrderPizzaEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Order' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoOrder() { return CreateRelationInfoForNavigator("Order"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Pizza' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPizza() { return CreateRelationInfoForNavigator("Pizza"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this OrderPizzaEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static OrderPizzaRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Order' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathOrder { get { return _staticMetaData.GetPrefetchPathElement("Order", CommonEntityBase.CreateEntityCollection<OrderEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Pizza' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPizza { get { return _staticMetaData.GetPrefetchPathElement("Pizza", CommonEntityBase.CreateEntityCollection<PizzaEntity>()); } }

		/// <summary>The OrderId property of the Entity OrderPizza<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OrderPizza"."OrderId".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 OrderId
		{
			get { return (System.Int64)GetValue((int)OrderPizzaFieldIndex.OrderId, true); }
			set	{ SetValue((int)OrderPizzaFieldIndex.OrderId, value); }
		}

		/// <summary>The PizzaId property of the Entity OrderPizza<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OrderPizza"."PizzaId".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 PizzaId
		{
			get { return (System.Int64)GetValue((int)OrderPizzaFieldIndex.PizzaId, true); }
			set	{ SetValue((int)OrderPizzaFieldIndex.PizzaId, value); }
		}

		/// <summary>The Size property of the Entity OrderPizza<br/><br/></summary>
		/// <remarks>Mapped on  table field: "OrderPizza"."Size".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.String Size
		{
			get { return (System.String)GetValue((int)OrderPizzaFieldIndex.Size, true); }
			set	{ SetValue((int)OrderPizzaFieldIndex.Size, value); }
		}

		/// <summary>Gets / sets related entity of type 'OrderEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual OrderEntity Order
		{
			get { return _order; }
			set { SetSingleRelatedEntityNavigator(value, "Order"); }
		}

		/// <summary>Gets / sets related entity of type 'PizzaEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PizzaEntity Pizza
		{
			get { return _pizza; }
			set { SetSingleRelatedEntityNavigator(value, "Pizza"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace PizzaOrder
{
	public enum OrderPizzaFieldIndex
	{
		///<summary>OrderId. </summary>
		OrderId,
		///<summary>PizzaId. </summary>
		PizzaId,
		///<summary>Size. </summary>
		Size,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace PizzaOrder.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: OrderPizza. </summary>
	public partial class OrderPizzaRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between OrderPizzaEntity and OrderEntity over the m:1 relation they have, using the relation between the fields: OrderPizza.OrderId - Order.Id</summary>
		public virtual IEntityRelation OrderEntityUsingOrderId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Order", false, new[] { OrderFields.Id, OrderPizzaFields.OrderId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between OrderPizzaEntity and PizzaEntity over the m:1 relation they have, using the relation between the fields: OrderPizza.PizzaId - Pizza.Id</summary>
		public virtual IEntityRelation PizzaEntityUsingPizzaId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Pizza", false, new[] { PizzaFields.Id, OrderPizzaFields.PizzaId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticOrderPizzaRelations
	{
		internal static readonly IEntityRelation OrderEntityUsingOrderIdStatic = new OrderPizzaRelations().OrderEntityUsingOrderId;
		internal static readonly IEntityRelation PizzaEntityUsingPizzaIdStatic = new OrderPizzaRelations().PizzaEntityUsingPizzaId;

		/// <summary>CTor</summary>
		static StaticOrderPizzaRelations() { }
	}
}
