//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using PizzaOrder.HelperClasses;
using PizzaOrder.FactoryClasses;
using PizzaOrder.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace PizzaOrder.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'PizzaTopping'.<br/><br/></summary>
	[Serializable]
	public partial class PizzaToppingEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private PizzaEntity _pizza;
		private ToppingEntity _topping;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static PizzaToppingEntityStaticMetaData _staticMetaData = new PizzaToppingEntityStaticMetaData();
		private static PizzaToppingRelations _relationsFactory = new PizzaToppingRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Pizza</summary>
			public static readonly string Pizza = "Pizza";
			/// <summary>Member name Topping</summary>
			public static readonly string Topping = "Topping";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class PizzaToppingEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public PizzaToppingEntityStaticMetaData()
			{
				SetEntityCoreInfo("PizzaToppingEntity", InheritanceHierarchyType.None, false, (int)PizzaOrder.EntityType.PizzaToppingEntity, typeof(PizzaToppingEntity), typeof(PizzaToppingEntityFactory), false);
				AddNavigatorMetaData<PizzaToppingEntity, PizzaEntity>("Pizza", "PizzaToppings", (a, b) => a._pizza = b, a => a._pizza, (a, b) => a.Pizza = b, PizzaOrder.RelationClasses.StaticPizzaToppingRelations.PizzaEntityUsingPizzaIdStatic, ()=>new PizzaToppingRelations().PizzaEntityUsingPizzaId, null, new int[] { (int)PizzaToppingFieldIndex.PizzaId }, null, true, (int)PizzaOrder.EntityType.PizzaEntity);
				AddNavigatorMetaData<PizzaToppingEntity, ToppingEntity>("Topping", "PizzaToppings", (a, b) => a._topping = b, a => a._topping, (a, b) => a.Topping = b, PizzaOrder.RelationClasses.StaticPizzaToppingRelations.ToppingEntityUsingToppingIdStatic, ()=>new PizzaToppingRelations().ToppingEntityUsingToppingId, null, new int[] { (int)PizzaToppingFieldIndex.ToppingId }, null, true, (int)PizzaOrder.EntityType.ToppingEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static PizzaToppingEntity()
		{
		}

		/// <summary> CTor</summary>
		public PizzaToppingEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public PizzaToppingEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this PizzaToppingEntity</param>
		public PizzaToppingEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="pizzaId">PK value for PizzaTopping which data should be fetched into this PizzaTopping object</param>
		/// <param name="toppingId">PK value for PizzaTopping which data should be fetched into this PizzaTopping object</param>
		public PizzaToppingEntity(System.Int64 pizzaId, System.Int64 toppingId) : this(pizzaId, toppingId, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="pizzaId">PK value for PizzaTopping which data should be fetched into this PizzaTopping object</param>
		/// <param name="toppingId">PK value for PizzaTopping which data should be fetched into this PizzaTopping object</param>
		/// <param name="validator">The custom validator object for this PizzaToppingEntity</param>
		public PizzaToppingEntity(System.Int64 pizzaId, System.Int64 toppingId, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.PizzaId = pizzaId;
			this.ToppingId = toppingId;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected PizzaToppingEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Pizza' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPizza() { return CreateRelationInfoForNavigator("Pizza"); }

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entity of type 'Topping' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoTopping() { return CreateRelationInfoForNavigator("Topping"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this PizzaToppingEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static PizzaToppingRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Pizza' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPizza { get { return _staticMetaData.GetPrefetchPathElement("Pizza", CommonEntityBase.CreateEntityCollection<PizzaEntity>()); } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Topping' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathTopping { get { return _staticMetaData.GetPrefetchPathElement("Topping", CommonEntityBase.CreateEntityCollection<ToppingEntity>()); } }

		/// <summary>The PizzaId property of the Entity PizzaTopping<br/><br/></summary>
		/// <remarks>Mapped on  table field: "PizzaToppings"."PizzaId".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 PizzaId
		{
			get { return (System.Int64)GetValue((int)PizzaToppingFieldIndex.PizzaId, true); }
			set	{ SetValue((int)PizzaToppingFieldIndex.PizzaId, value); }
		}

		/// <summary>The ToppingId property of the Entity PizzaTopping<br/><br/></summary>
		/// <remarks>Mapped on  table field: "PizzaToppings"."ToppingId".<br/>Table field type characteristics (type, precision, scale, length): Bigint, 20, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.Int64 ToppingId
		{
			get { return (System.Int64)GetValue((int)PizzaToppingFieldIndex.ToppingId, true); }
			set	{ SetValue((int)PizzaToppingFieldIndex.ToppingId, value); }
		}

		/// <summary>Gets / sets related entity of type 'PizzaEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual PizzaEntity Pizza
		{
			get { return _pizza; }
			set { SetSingleRelatedEntityNavigator(value, "Pizza"); }
		}

		/// <summary>Gets / sets related entity of type 'ToppingEntity' which has to be set using a fetch action earlier. If no related entity is set for this property, null is returned..<br/><br/></summary>
		[Browsable(false)]
		public virtual ToppingEntity Topping
		{
			get { return _topping; }
			set { SetSingleRelatedEntityNavigator(value, "Topping"); }
		}
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace PizzaOrder
{
	public enum PizzaToppingFieldIndex
	{
		///<summary>PizzaId. </summary>
		PizzaId,
		///<summary>ToppingId. </summary>
		ToppingId,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace PizzaOrder.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: PizzaTopping. </summary>
	public partial class PizzaToppingRelations: RelationFactory
	{

		/// <summary>Returns a new IEntityRelation object, between PizzaToppingEntity and PizzaEntity over the m:1 relation they have, using the relation between the fields: PizzaTopping.PizzaId - Pizza.Id</summary>
		public virtual IEntityRelation PizzaEntityUsingPizzaId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Pizza", false, new[] { PizzaFields.Id, PizzaToppingFields.PizzaId }); }
		}

		/// <summary>Returns a new IEntityRelation object, between PizzaToppingEntity and ToppingEntity over the m:1 relation they have, using the relation between the fields: PizzaTopping.ToppingId - Topping.Id</summary>
		public virtual IEntityRelation ToppingEntityUsingToppingId
		{
			get	{ return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.ManyToOne, "Topping", false, new[] { ToppingFields.Id, PizzaToppingFields.ToppingId }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticPizzaToppingRelations
	{
		internal static readonly IEntityRelation PizzaEntityUsingPizzaIdStatic = new PizzaToppingRelations().PizzaEntityUsingPizzaId;
		internal static readonly IEntityRelation ToppingEntityUsingToppingIdStatic = new PizzaToppingRelations().ToppingEntityUsingToppingId;

		/// <summary>CTor</summary>
		static StaticPizzaToppingRelations() { }
	}
}
