//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace ToppingsOnPizza.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Pizza'.</summary>
	[Serializable]
	[DataContract]
	public partial class ToppingsOnPizza
	{
		/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Pizza.Id'</summary>
		[DataMember]
		public System.Int64 Id { get; set; }
		/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Pizza.Name'</summary>
		[DataMember]
		public System.String Name { get; set; }
		/// <summary>Gets or sets the PizzaToppings field. </summary>
		[DataMember]
		public List<ToppingsOnPizzaTypes.PizzaTopping> PizzaToppings { get; set; }
		/// <summary>Gets or sets the Size field. Derived from Entity Model Field 'Pizza.Size'</summary>
		[DataMember]
		public System.String Size { get; set; }
	}

	namespace ToppingsOnPizzaTypes
	{
		/// <summary> DTO class which is derived from the entity 'PizzaTopping (PizzaToppings)'.</summary>
		[Serializable]
		[DataContract]
		public partial class PizzaTopping
		{
			/// <summary>Gets or sets the Topping field. </summary>
			[DataMember]
			public PizzaToppingTypes.Topping Topping { get; set; }
		}

		namespace PizzaToppingTypes
		{
			/// <summary> DTO class which is derived from the entity 'Topping (PizzaToppings.Topping)'.</summary>
			[Serializable]
			[DataContract]
			public partial class Topping
			{
				/// <summary>Gets or sets the Id field. Derived from Entity Model Field 'Topping.Id'</summary>
				[DataMember]
				public System.Int64 Id { get; set; }
				/// <summary>Gets or sets the Name field. Derived from Entity Model Field 'Topping.Name'</summary>
				[DataMember]
				public System.String Name { get; set; }
				/// <summary>Gets or sets the Price field. Derived from Entity Model Field 'Topping.Price'</summary>
				[DataMember]
				public System.Double Price { get; set; }
			}
		}
	}

}




